steps:
- name: gcr.io/cloud-builders/gcloud
  dir: app
  args:
  - kms
  - decrypt
  - --ciphertext-file=hikma-health-098c787f1bcd.json.enc
  - --plaintext-file=hikma-health-098c787f1bcd.json
  - --location=global
  - --keyring=hikma-demo-keyring
  - --key=hikma-demo-key
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'credential_file_arg=hikma-health-098c787f1bcd.json',
          '--build-arg', 'db_instance_arg=${_DB_INSTANCE}',
          '--build-arg', 'commit_sha_arg=$COMMIT_SHA',
          '--build-arg', 'db_password_arg=${_DB_PASSWORD}',
          '--build-arg', 'photos_storage_bucket_arg=${_PHOTOS_STORAGE_BUCKET}',
          '.' ]
  dir: app
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=us-east1-b', 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster']
  args: ['set', 'image', 'deployment/hikma-health-backend',
          'hikma-health-backend=gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA'
substitutions:
  _DB_INSTANCE: 'hikma-health:us-east1:hikma-db-demo'
options:
  machineType: 'N1_HIGHCPU_8'
